### ISSUE TITLE
"addRouterAttributesToFormRequest()" does not forward parameter to controller when using "createFormViewBuilder()"

### ISSUE THREAD

**Issue by cyrille-chene** [sulu/sulu-demo#112]
| Q | A
| --- | ---
| Bug? | Yes
| New Feature? | no
| Sulu Version | Sulu 2.5
| Browser Version | Chrome Version 121.0.6167.185

#### Actual Behavior

When following this example : https://github.com/sulu/sulu-demo/pull/106/files
WebspaceSettingController.php uses request to check for permission with getSecurityContext() and the webspace parameter.
In this case the webspace parameter doesn't exist

#### Expected Behavior

Webspace parameter should be forwarded from the FromView with the "addRouterAttributesToFormRequest()" method.

#### Steps to Reproduce

You can follow the example https://github.com/sulu/sulu-demo/pull/106/files.
You should get an error 403 when accessing the tab in admin BO saying : "context 'sulu.webspaces..setting"
Between the 2 dots is supposed to be the webspace key of the webspace selected in the Back Office.

#### Possible Solutions

It seems to be in the javascript part of Sulu but i did not investigate it more because of a lake of knowledge here

**Comment by manuxi** [comment]
I digged a bit but had to take a break. I commented out the security stuff, but it's still not working. In my WebspaceSettingsController $request->query->all() is empty.
```
/*
 * @Route("/webspace-settings/{id}", methods={"GET"}, name="get_webspace_settings")
 * /
public function getAction(Request $request): Response
```
routes_admin.yml is as follows
```
sulu_webspace_settings_api:
    type: annotation
    prefix: /admin/api
    resource: Manuxi\SuluWebspaceSettingsBundle\Controller\Admin\WebspaceSettingsController
    name_prefix: sulu_webspace_settings.
    options:
        expose: true
```
