### ISSUE TITLE
Add Docker support

### ISSUE THREAD

**Issue by gram7gram** [sulu/sulu-demo#40]
I have found your repository and have tried to make it up and running.

It is a **pain**.

Add `Docker` and `Docker-compose` support for your `development` environment.

Something like this will be a good start:
```yml
version: '3.1'

services:

  sulu-01:
    container_name: sulu-01
    build: ./env-config
    ports:
      - '15300:80'
    volumes:
      - '.:/var/www/html'
      - './env-config/apache/000-default.conf:/etc/apache2/sites-available/000-default.conf'
      - './env-config/composer.phar:/usr/bin/composer'
    depends_on:
      - sulu-mysql-master
      - sulu-elasticsearch-master

  sulu-elasticsearch-master:
    container_name: sulu-elasticsearch-master
    hostname: sulu-elasticsearch-master
    image: docker.elastic.co/elasticsearch/elasticsearch-platinum:6.1.2
    ports:
      - '15302:9200'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    environment:
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
    volumes:
      - '.persistence/elasticsearch/5:/data/sw/elasticsearch/data'

  sulu-mysql-master:
    container_name: sulu-mysql-master
    hostname: sulu-mysql-master
    image: 'mysql:5'
    ports:
      - '15301:3306'
    environment:
      MYSQL_USER: suluadmin
      MYSQL_DATABASE: sulu
      MYSQL_PASSWORD: 12345
      MYSQL_ROOT_PASSWORD: 54321
    volumes:
      - '.persistence/mysql/5:/var/lib/mysql'
```

Meanwhile, if I accomplish working environment, I will try to create a PR for this.
