### ISSUE TITLE
Add Elasticsearch configuration

### ISSUE THREAD

**Issue by gram7gram** [sulu/sulu-demo#41]
Not all elasticsearch instances are at `localhost:9200`, so you need to specify in `config.yml` at least `host` and `port` keys.

Naturally, values should be specified in `parameters.yml`.

`parameters.yml`
```yml
parameters:
    ....
    elastica.master.host: master.sulu-elasticsearch-master.com
    elastica.master.port: 9200
    elastica.node-01.host: node-01.sulu-elasticsearch-master.com
    elastica.node-01.port: 9200
    ....
```

`config.yml`
```yml
ongr_elasticsearch:
    ...
    managers:
        default:
            index: 
                hosts:
                    - '%elastica.master.host%:%elastica.master.port%'
                    - '%elastica.node-01.host%:%elastica.node-01.port%'
            ...
```
